/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ANumberRouteImport } from './routes/a.$number'
import { Route as AdminGuardRouteRouteImport } from './routes/admin/_guard/route'
import { Route as AgentGuardRouteRouteImport } from './routes/agent/_guard/route'
import { Route as AgentLoginRouteImport } from './routes/agent/login'
import { Route as EtablissementNumberRouteImport } from './routes/etablissement.$number'
import { Route as AdminGuardIndexRouteImport } from './routes/admin/_guard/index'
import { Route as AdminGuardAddressesRouteImport } from './routes/admin/_guard/addresses'
import { Route as AdminGuardAgentsRouteImport } from './routes/admin/_guard/agents'
import { Route as AdminGuardBeaconsRouteImport } from './routes/admin/_guard/beacons'
import { Route as AdminGuardInstallationsRouteImport } from './routes/admin/_guard/installations'
import { Route as AdminGuardLotsRouteImport } from './routes/admin/_guard/lots'
import { Route as AdminGuardReportsRouteImport } from './routes/admin/_guard/reports'
import { Route as AdminGuardUsersRouteImport } from './routes/admin/_guard/users'
import { Route as AgentGuardIndexRouteImport } from './routes/agent/_guard/index'
import { Route as AgentGuardHistoryRouteImport } from './routes/agent/_guard/history'
import { Route as AgentGuardProfileRouteImport } from './routes/agent/_guard/profile'
import { Route as AgentGuardSyncIssuesRouteImport } from './routes/agent/_guard/sync-issues'
import { Route as AgentGuardTasksRouteImport } from './routes/agent/_guard/tasks'
import { Route as AgentGuardInstallNumberRouteImport } from './routes/agent/_guard/install.$number'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ANumberRoute = ANumberRouteImport.update({
  id: '/a/$number',
  path: '/a/$number',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGuardRouteRoute = AdminGuardRouteRouteImport.update({
  id: '/admin/_guard',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentGuardRouteRoute = AgentGuardRouteRouteImport.update({
  id: '/agent/_guard',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentLoginRoute = AgentLoginRouteImport.update({
  id: '/agent/login',
  path: '/agent/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EtablissementNumberRoute = EtablissementNumberRouteImport.update({
  id: '/etablissement/$number',
  path: '/etablissement/$number',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGuardIndexRoute = AdminGuardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminGuardRouteRoute,
} as any)
const AdminGuardAddressesRoute = AdminGuardAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => AdminGuardRouteRoute,
} as any)
const AdminGuardAgentsRoute = AdminGuardAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AdminGuardRouteRoute,
} as any)
const AdminGuardBeaconsRoute = AdminGuardBeaconsRouteImport.update({
  id: '/beacons',
  path: '/beacons',
  getParentRoute: () => AdminGuardRouteRoute,
} as any)
const AdminGuardInstallationsRoute = AdminGuardInstallationsRouteImport.update({
  id: '/installations',
  path: '/installations',
  getParentRoute: () => AdminGuardRouteRoute,
} as any)
const AdminGuardLotsRoute = AdminGuardLotsRouteImport.update({
  id: '/lots',
  path: '/lots',
  getParentRoute: () => AdminGuardRouteRoute,
} as any)
const AdminGuardReportsRoute = AdminGuardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminGuardRouteRoute,
} as any)
const AdminGuardUsersRoute = AdminGuardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminGuardRouteRoute,
} as any)
const AgentGuardIndexRoute = AgentGuardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentGuardRouteRoute,
} as any)
const AgentGuardHistoryRoute = AgentGuardHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AgentGuardRouteRoute,
} as any)
const AgentGuardProfileRoute = AgentGuardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AgentGuardRouteRoute,
} as any)
const AgentGuardSyncIssuesRoute = AgentGuardSyncIssuesRouteImport.update({
  id: '/sync-issues',
  path: '/sync-issues',
  getParentRoute: () => AgentGuardRouteRoute,
} as any)
const AgentGuardTasksRoute = AgentGuardTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AgentGuardRouteRoute,
} as any)
const AgentGuardInstallNumberRoute = AgentGuardInstallNumberRouteImport.update({
  id: '/install/$number',
  path: '/install/$number',
  getParentRoute: () => AgentGuardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AdminGuardRouteRouteWithChildren
  '/agent': typeof AgentGuardRouteRouteWithChildren
  '/a/$number': typeof ANumberRoute
  '/agent/login': typeof AgentLoginRoute
  '/etablissement/$number': typeof EtablissementNumberRoute
  '/admin/addresses': typeof AdminGuardAddressesRoute
  '/admin/agents': typeof AdminGuardAgentsRoute
  '/admin/beacons': typeof AdminGuardBeaconsRoute
  '/admin/installations': typeof AdminGuardInstallationsRoute
  '/admin/lots': typeof AdminGuardLotsRoute
  '/admin/reports': typeof AdminGuardReportsRoute
  '/admin/users': typeof AdminGuardUsersRoute
  '/agent/history': typeof AgentGuardHistoryRoute
  '/agent/profile': typeof AgentGuardProfileRoute
  '/agent/sync-issues': typeof AgentGuardSyncIssuesRoute
  '/agent/tasks': typeof AgentGuardTasksRoute
  '/admin/': typeof AdminGuardIndexRoute
  '/agent/': typeof AgentGuardIndexRoute
  '/agent/install/$number': typeof AgentGuardInstallNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/a/$number': typeof ANumberRoute
  '/agent/login': typeof AgentLoginRoute
  '/etablissement/$number': typeof EtablissementNumberRoute
  '/admin/addresses': typeof AdminGuardAddressesRoute
  '/admin/agents': typeof AdminGuardAgentsRoute
  '/admin/beacons': typeof AdminGuardBeaconsRoute
  '/admin/installations': typeof AdminGuardInstallationsRoute
  '/admin/lots': typeof AdminGuardLotsRoute
  '/admin/reports': typeof AdminGuardReportsRoute
  '/admin/users': typeof AdminGuardUsersRoute
  '/agent/history': typeof AgentGuardHistoryRoute
  '/agent/profile': typeof AgentGuardProfileRoute
  '/agent/sync-issues': typeof AgentGuardSyncIssuesRoute
  '/agent/tasks': typeof AgentGuardTasksRoute
  '/admin': typeof AdminGuardIndexRoute
  '/agent': typeof AgentGuardIndexRoute
  '/agent/install/$number': typeof AgentGuardInstallNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/admin/_guard': typeof AdminGuardRouteRouteWithChildren
  '/agent/_guard': typeof AgentGuardRouteRouteWithChildren
  '/a/$number': typeof ANumberRoute
  '/agent/login': typeof AgentLoginRoute
  '/etablissement/$number': typeof EtablissementNumberRoute
  '/admin/_guard/addresses': typeof AdminGuardAddressesRoute
  '/admin/_guard/agents': typeof AdminGuardAgentsRoute
  '/admin/_guard/beacons': typeof AdminGuardBeaconsRoute
  '/admin/_guard/installations': typeof AdminGuardInstallationsRoute
  '/admin/_guard/lots': typeof AdminGuardLotsRoute
  '/admin/_guard/reports': typeof AdminGuardReportsRoute
  '/admin/_guard/users': typeof AdminGuardUsersRoute
  '/agent/_guard/history': typeof AgentGuardHistoryRoute
  '/agent/_guard/profile': typeof AgentGuardProfileRoute
  '/agent/_guard/sync-issues': typeof AgentGuardSyncIssuesRoute
  '/agent/_guard/tasks': typeof AgentGuardTasksRoute
  '/admin/_guard/': typeof AdminGuardIndexRoute
  '/agent/_guard/': typeof AgentGuardIndexRoute
  '/agent/_guard/install/$number': typeof AgentGuardInstallNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/confidentialite'
    | '/login'
    | '/logout'
    | '/signup'
    | '/admin'
    | '/agent'
    | '/a/$number'
    | '/agent/login'
    | '/etablissement/$number'
    | '/admin/addresses'
    | '/admin/agents'
    | '/admin/beacons'
    | '/admin/installations'
    | '/admin/lots'
    | '/admin/reports'
    | '/admin/users'
    | '/agent/history'
    | '/agent/profile'
    | '/agent/sync-issues'
    | '/agent/tasks'
    | '/admin/'
    | '/agent/'
    | '/agent/install/$number'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/confidentialite'
    | '/login'
    | '/logout'
    | '/signup'
    | '/a/$number'
    | '/agent/login'
    | '/etablissement/$number'
    | '/admin/addresses'
    | '/admin/agents'
    | '/admin/beacons'
    | '/admin/installations'
    | '/admin/lots'
    | '/admin/reports'
    | '/admin/users'
    | '/agent/history'
    | '/agent/profile'
    | '/agent/sync-issues'
    | '/agent/tasks'
    | '/admin'
    | '/agent'
    | '/agent/install/$number'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/confidentialite'
    | '/login'
    | '/logout'
    | '/signup'
    | '/admin/_guard'
    | '/agent/_guard'
    | '/a/$number'
    | '/agent/login'
    | '/etablissement/$number'
    | '/admin/_guard/addresses'
    | '/admin/_guard/agents'
    | '/admin/_guard/beacons'
    | '/admin/_guard/installations'
    | '/admin/_guard/lots'
    | '/admin/_guard/reports'
    | '/admin/_guard/users'
    | '/agent/_guard/history'
    | '/agent/_guard/profile'
    | '/agent/_guard/sync-issues'
    | '/agent/_guard/tasks'
    | '/admin/_guard/'
    | '/agent/_guard/'
    | '/agent/_guard/install/$number'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  SignupRoute: typeof SignupRoute
  AdminGuardRouteRoute: typeof AdminGuardRouteRouteWithChildren
  AgentGuardRouteRoute: typeof AgentGuardRouteRouteWithChildren
  ANumberRoute: typeof ANumberRoute
  AgentLoginRoute: typeof AgentLoginRoute
  EtablissementNumberRoute: typeof EtablissementNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a/$number': {
      id: '/a/$number'
      path: '/a/$number'
      fullPath: '/a/$number'
      preLoaderRoute: typeof ANumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_guard': {
      id: '/admin/_guard'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminGuardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/_guard': {
      id: '/agent/_guard'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentGuardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/login': {
      id: '/agent/login'
      path: '/agent/login'
      fullPath: '/agent/login'
      preLoaderRoute: typeof AgentLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etablissement/$number': {
      id: '/etablissement/$number'
      path: '/etablissement/$number'
      fullPath: '/etablissement/$number'
      preLoaderRoute: typeof EtablissementNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_guard/': {
      id: '/admin/_guard/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminGuardIndexRouteImport
      parentRoute: typeof AdminGuardRouteRoute
    }
    '/admin/_guard/addresses': {
      id: '/admin/_guard/addresses'
      path: '/addresses'
      fullPath: '/admin/addresses'
      preLoaderRoute: typeof AdminGuardAddressesRouteImport
      parentRoute: typeof AdminGuardRouteRoute
    }
    '/admin/_guard/agents': {
      id: '/admin/_guard/agents'
      path: '/agents'
      fullPath: '/admin/agents'
      preLoaderRoute: typeof AdminGuardAgentsRouteImport
      parentRoute: typeof AdminGuardRouteRoute
    }
    '/admin/_guard/beacons': {
      id: '/admin/_guard/beacons'
      path: '/beacons'
      fullPath: '/admin/beacons'
      preLoaderRoute: typeof AdminGuardBeaconsRouteImport
      parentRoute: typeof AdminGuardRouteRoute
    }
    '/admin/_guard/installations': {
      id: '/admin/_guard/installations'
      path: '/installations'
      fullPath: '/admin/installations'
      preLoaderRoute: typeof AdminGuardInstallationsRouteImport
      parentRoute: typeof AdminGuardRouteRoute
    }
    '/admin/_guard/lots': {
      id: '/admin/_guard/lots'
      path: '/lots'
      fullPath: '/admin/lots'
      preLoaderRoute: typeof AdminGuardLotsRouteImport
      parentRoute: typeof AdminGuardRouteRoute
    }
    '/admin/_guard/reports': {
      id: '/admin/_guard/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminGuardReportsRouteImport
      parentRoute: typeof AdminGuardRouteRoute
    }
    '/admin/_guard/users': {
      id: '/admin/_guard/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminGuardUsersRouteImport
      parentRoute: typeof AdminGuardRouteRoute
    }
    '/agent/_guard/': {
      id: '/agent/_guard/'
      path: '/'
      fullPath: '/agent/'
      preLoaderRoute: typeof AgentGuardIndexRouteImport
      parentRoute: typeof AgentGuardRouteRoute
    }
    '/agent/_guard/history': {
      id: '/agent/_guard/history'
      path: '/history'
      fullPath: '/agent/history'
      preLoaderRoute: typeof AgentGuardHistoryRouteImport
      parentRoute: typeof AgentGuardRouteRoute
    }
    '/agent/_guard/profile': {
      id: '/agent/_guard/profile'
      path: '/profile'
      fullPath: '/agent/profile'
      preLoaderRoute: typeof AgentGuardProfileRouteImport
      parentRoute: typeof AgentGuardRouteRoute
    }
    '/agent/_guard/sync-issues': {
      id: '/agent/_guard/sync-issues'
      path: '/sync-issues'
      fullPath: '/agent/sync-issues'
      preLoaderRoute: typeof AgentGuardSyncIssuesRouteImport
      parentRoute: typeof AgentGuardRouteRoute
    }
    '/agent/_guard/tasks': {
      id: '/agent/_guard/tasks'
      path: '/tasks'
      fullPath: '/agent/tasks'
      preLoaderRoute: typeof AgentGuardTasksRouteImport
      parentRoute: typeof AgentGuardRouteRoute
    }
    '/agent/_guard/install/$number': {
      id: '/agent/_guard/install/$number'
      path: '/install/$number'
      fullPath: '/agent/install/$number'
      preLoaderRoute: typeof AgentGuardInstallNumberRouteImport
      parentRoute: typeof AgentGuardRouteRoute
    }
  }
}

interface AdminGuardRouteRouteChildren {
  AdminGuardAddressesRoute: typeof AdminGuardAddressesRoute
  AdminGuardAgentsRoute: typeof AdminGuardAgentsRoute
  AdminGuardBeaconsRoute: typeof AdminGuardBeaconsRoute
  AdminGuardInstallationsRoute: typeof AdminGuardInstallationsRoute
  AdminGuardLotsRoute: typeof AdminGuardLotsRoute
  AdminGuardReportsRoute: typeof AdminGuardReportsRoute
  AdminGuardUsersRoute: typeof AdminGuardUsersRoute
  AdminGuardIndexRoute: typeof AdminGuardIndexRoute
}

const AdminGuardRouteRouteChildren: AdminGuardRouteRouteChildren = {
  AdminGuardAddressesRoute: AdminGuardAddressesRoute,
  AdminGuardAgentsRoute: AdminGuardAgentsRoute,
  AdminGuardBeaconsRoute: AdminGuardBeaconsRoute,
  AdminGuardInstallationsRoute: AdminGuardInstallationsRoute,
  AdminGuardLotsRoute: AdminGuardLotsRoute,
  AdminGuardReportsRoute: AdminGuardReportsRoute,
  AdminGuardUsersRoute: AdminGuardUsersRoute,
  AdminGuardIndexRoute: AdminGuardIndexRoute,
}

const AdminGuardRouteRouteWithChildren = AdminGuardRouteRoute._addFileChildren(
  AdminGuardRouteRouteChildren,
)

interface AgentGuardRouteRouteChildren {
  AgentGuardHistoryRoute: typeof AgentGuardHistoryRoute
  AgentGuardProfileRoute: typeof AgentGuardProfileRoute
  AgentGuardSyncIssuesRoute: typeof AgentGuardSyncIssuesRoute
  AgentGuardTasksRoute: typeof AgentGuardTasksRoute
  AgentGuardIndexRoute: typeof AgentGuardIndexRoute
  AgentGuardInstallNumberRoute: typeof AgentGuardInstallNumberRoute
}

const AgentGuardRouteRouteChildren: AgentGuardRouteRouteChildren = {
  AgentGuardHistoryRoute: AgentGuardHistoryRoute,
  AgentGuardProfileRoute: AgentGuardProfileRoute,
  AgentGuardSyncIssuesRoute: AgentGuardSyncIssuesRoute,
  AgentGuardTasksRoute: AgentGuardTasksRoute,
  AgentGuardIndexRoute: AgentGuardIndexRoute,
  AgentGuardInstallNumberRoute: AgentGuardInstallNumberRoute,
}

const AgentGuardRouteRouteWithChildren = AgentGuardRouteRoute._addFileChildren(
  AgentGuardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  SignupRoute: SignupRoute,
  AdminGuardRouteRoute: AdminGuardRouteRouteWithChildren,
  AgentGuardRouteRoute: AgentGuardRouteRouteWithChildren,
  ANumberRoute: ANumberRoute,
  AgentLoginRoute: AgentLoginRoute,
  EtablissementNumberRoute: EtablissementNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
