/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ANumberRouteImport } from './routes/a.$number'
import { Route as AgentGuardRouteRouteImport } from './routes/agent/_guard/route'
import { Route as EtablissementNumberRouteImport } from './routes/etablissement.$number'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ANumberRoute = ANumberRouteImport.update({
  id: '/a/$number',
  path: '/a/$number',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentGuardRouteRoute = AgentGuardRouteRouteImport.update({
  id: '/agent/_guard',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const EtablissementNumberRoute = EtablissementNumberRouteImport.update({
  id: '/etablissement/$number',
  path: '/etablissement/$number',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/agent': typeof AgentGuardRouteRoute
  '/a/$number': typeof ANumberRoute
  '/etablissement/$number': typeof EtablissementNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/agent': typeof AgentGuardRouteRoute
  '/a/$number': typeof ANumberRoute
  '/etablissement/$number': typeof EtablissementNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/agent/_guard': typeof AgentGuardRouteRoute
  '/a/$number': typeof ANumberRoute
  '/etablissement/$number': typeof EtablissementNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/confidentialite'
    | '/login'
    | '/logout'
    | '/signup'
    | '/agent'
    | '/a/$number'
    | '/etablissement/$number'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/confidentialite'
    | '/login'
    | '/logout'
    | '/signup'
    | '/agent'
    | '/a/$number'
    | '/etablissement/$number'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/confidentialite'
    | '/login'
    | '/logout'
    | '/signup'
    | '/agent/_guard'
    | '/a/$number'
    | '/etablissement/$number'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  SignupRoute: typeof SignupRoute
  AgentGuardRouteRoute: typeof AgentGuardRouteRoute
  ANumberRoute: typeof ANumberRoute
  EtablissementNumberRoute: typeof EtablissementNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a/$number': {
      id: '/a/$number'
      path: '/a/$number'
      fullPath: '/a/$number'
      preLoaderRoute: typeof ANumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/_guard': {
      id: '/agent/_guard'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentGuardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etablissement/$number': {
      id: '/etablissement/$number'
      path: '/etablissement/$number'
      fullPath: '/etablissement/$number'
      preLoaderRoute: typeof EtablissementNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  SignupRoute: SignupRoute,
  AgentGuardRouteRoute: AgentGuardRouteRoute,
  ANumberRoute: ANumberRoute,
  EtablissementNumberRoute: EtablissementNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
